### ISSUE TITLE
Test intermittently failing because to2.ProveOVHdr failing due to finalizer clearing xA

### ISSUE THREAD

**Issue by bkgoodman** [fido-device-onboard/go-fdo#20]
I am running `go test` in an external  (shell-script) loop - and getting a failure like once out of every 5 or 10 cycles. It is a:

`TO2.ProveOVHdr payload signature verification failed: cryptographic verification failed`
 
...in to2.ProveOVHdr verification. Keys look consistent between sign and verify, but payload is not - xA is getting cleared _between_ the signing and verifying. Adding some debug as such...

```
        // The lifetime of xA is until the transport has marshaled and sent the proof. Therefore, the
        // best option for clearing the secret is to set a finalizer (unfortunately).
        proof := s1.Tag()
        runtime.SetFinalizer(proof, func(proof *cose.Sign1Tag[ovhProof, []byte]) {
                fmt.Printf("*** FINALIZER CLEARING!!!!\n")
                clear(proof.Payload.Val.KeyExchangeA)
        })
```
...has proven that the finalizer is getting called between signing and verifying in these cases.

I am a bit unclear on when/how this finalizer is _supposed_ to be called, and why it may be triggered prematurely - once and a while...

**Comment by ben-krieger** [comment]
Thank you for making progress on this flaking test! I think we're just missing a runtime.KeepAlive in one spot of TO2. I will find it.

**Comment by bkgoodman** [comment]
I just got another failure.

I did notice that you added the `defer clear` - but never removed the old Runtime Finalizer. It appears as though the finalizer cleared in the case I `ran:`

```
*** SIGN OVHPROOF with key RSA2048 Fingerprint: 1dc0424e52b976c298d2988ee973541b2ae1be46822a5b1222827f19ade94987
*** FINALIZER CLEARING!!!!
*** FINALIZER CLEARING!!!!
*** VERIFY OVHPROOF with key RSA2048 Fingerprint: 1dc0424e52b976c298d2988ee973541b2ae1be46822a5b1222827f19ade94987
*** KeyExchangeA Set to [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
```

` defer clear(proveOVHdr.Payload.Val.KeyExchangeA)`
... is still in `sendHelloDevice`, but...


```
        runtime.SetFinalizer(proof, func(proof *cose.Sign1Tag[ovhProof, []byte]) {
                fmt.Printf("*** FINALIZER CLEARING!!!!\n")
                clear(proof.Payload.Val.KeyExchangeA)
        })
```

... is still in `proveOVHHdr`.
