### ISSUE TITLE
Marshalling of CBOR data doesn't work properly while saving credentials to a file for ARM-v5(32-bit) platform

### ISSUE THREAD

**Issue by shivagurija** [fido-device-onboard/go-fdo#6]
### Nature of the bug
Spec non-conformance which is specific to arm32-v5 platform. 
It works fine in ubuntu/Debian environment

### Steps taken to find bug

What did you do to trigger the bug?
Golang FDO client is built for ARM platform with build configurations `CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5`
Once Client is started, DI process is completed with manufacturer. However, while saving credentials to cred.bin file, we observe that Version, DeviceInfo, RVInfo and GUID are not written correctly. These fields have all default (0) values written to file.

Below content is written to file:
blobcred[
  Active        true
  Version       0
  DeviceInfo   ""
 GUID          00000000000000000000000000000000 
PublicKeyHash
   Algorithm   Sha384Hash
   Value       1370f27bcfbd9c39c88c0cd81b94b19d2ccb833acea86625ad8fed212d3d2dcbce2c556b070a9507144b61e7f482d9af
HmacSecret    <valid value>
PrivateKey    *ecdsa.PrivateKey
 &{PublicKey:{valid value}
RvInfo
]

### Steps to ensure bug is gone

How can a fix be validated?
Run go-fdo client in arm platform 32bit architecture.

### Optional: Reproduction

Do you have an exact list of commands for others to reproduce the problem?
Build client for ARM platform with build configurations `CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5`
Setup fdo-server
Run Client for DI
verify the credentials stored in cred.bin file (or) run client again for TO1/TO2 to observe the content written to cred.bin file.

### Client Debug Logs

```console
Writing Blob: blobcred[
 Active        true
 Version       101
 DeviceInfo   "FDOClientDevice"
 GUID          053f617d64824358bfe0723b2446a8be
 PublicKeyHash
   Algorithm   Sha384Hash
   Value       1370f27bcfbd9c39c88c0cd81b94b19d2ccb833acea86625ad8fed212d3d2dcbce2c556b070a9507144b61e7f482d9af
 HmacSecret    508a689131a5739359baab1f6dc5e53cd03aa9101205f689a96c6a8de78a1b21
 PrivateKey    *ecdsa.PrivateKey
   &{PublicKey:{Curve:0x6d9888 X:+1077014277194132773053583814475896633172137502038947349575041323424486881295764558294126705658152607350210191056430 Y:+23393307422916252606512308539302702261449660005695390980125883646074856080205038519324102642155259582270546606410346} D:+1515889814377831623117040235003995022127186260387224519891742875972738228521438566575788192991190076294051642279935}
 RvInfo
   >
     5 = 6d31302e3232372e3234382e3439
     3 = 191f68
       12 = 01
       4 = 191f68
 ]

 contents are written to the file: cred.bin
 File size is:  276
 GUID: 053f617d64824358bfe0723b2446a8be

 Read data from cred.bin: blobcred[
  Active        true
  Version       0
  DeviceInfo   ""
  GUID          00000000000000000000000000000000
  PublicKeyHash
    Algorithm   Sha384Hash
    Value       1370f27bcfbd9c39c88c0cd81b94b19d2ccb833acea86625ad8fed212d3d2dcbce2c556b070a9507144b61e7f482d9af
  HmacSecret    508a689131a5739359baab1f6dc5e53cd03aa9101205f689a96c6a8de78a1b21
  PrivateKey    *ecdsa.PrivateKey
    &{PublicKey:{Curve:0x6d9888 X:+1077014277194132773053583814475896633172137502038947349575041323424486881295764558294126705658152607350210191056430 Y:+23393307422916252606512308539302702261449660005695390980125883646074856080205038519324102642155259582270546606410346} D:+1515889814377831623117040235003995022127186260387224519891742875972738228521438566575788192991190076294051642279935}
    RvInfo
  ]
  GUID is: 00000000000000000000000000000000
```

**Comment by ben-krieger** [comment]
@shivagurija Can you run `go test ./cbor` in an ARM32 environment? It seems like struct embedding isn't working as expected. Nothing about using the reflect package should differ by architecture, so this is very surprising.

**Comment by ben-krieger** [comment]
I cannot reproduce this:

```console
➤ GOARCH=arm GOARM=5 go test -c -o test.arm32 ./cbor
➤ qemu-arm ./test.arm32
PASS
```
